### ISSUE TITLE
L-LMc (ODIN character n-gram feature)

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#10]
Implement the character n-gram feature for ODIN data. Use the `character-n-gram-size` parameter in the config file and the character_ngrams() function in analyzers.py to compute the n-grams. Use the model stored at the `odin-language-model` path (defined in the config file).

**Comment by goodmami** [comment]
This could also use a commit hash to help link commits to issues.

**Comment by MackieBlackburn** [comment]
https://github.com/xigt/lgid/commit/354a81fe642b9bf23d6443ac955b87bda60fe578

I didn't use the ngrams functions from analyzers.py but I will switch over to using those as there is no reason not to.

**Comment by elirnm** [comment]
Does that commit actually extract this feature out of the n-grams or just create the LMs themselves?

Same question for #8

**Comment by goodmami** [comment]
Ah I didn't notice that you weren't using those functions.

And as @elirnm says, we need to get the actual feature vectors so we can output them as intermediate results.

Otherwise, though, it's nice to use SciKit-Learn components when possible, so if you use CountVectorizer, change the invocation to match our model a bit better. Character n-grams are per word and not per line, so at least use the `char_wb` analyzer instead of `char`. But the `char_wb` analyzer doesn't allow for custom boundary characters, and always uses spaces on both ends (e.g. the bigrams for 'dog' are `[' d', 'do', 'og', 'g ']`). Instead, you can our analyzers.character_ngrams() function as the analyzer for the vectorizer. You'll want to modify that function to allow an n-gram range rather than a single n. That is:

```python
countsC = CountVectorizer(analyzer=lambda doc: analyzers.character_ngrams(doc, (m, n), lhs, rhs))
```

and

```python
def character_ngrams(s, ngram_range, lhs='<', rhs='>'):
    ...  # (modified accordingly for ngram_range)
```

lhs and rhs can be config parameters. The default values are what's used in Crubadan, I think.
