### ISSUE TITLE
L-CR-LMw (Crubadan word n-gram feature)

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#11]
Implement the word n-gram feature for Crubadan data. Use the `word-n-gram-size` parameter in the config file and the word_ngrams() function in analyzers.py to compute the n-grams. Use the model stored at the `crubadan-language-model` path (defined in the config file).

**Comment by elirnm** [comment]
A question about the `read_crubadan_language_model` method (which I'm currently working on implementing): is the path supposed to go to a specific LM file for a specific language and the method just reads that file into a data structure, or is it supposed to read everything under the crudaban_lm folder into a much larger data structure containing everything?

**Comment by elirnm** [comment]
Also, do we care about the count part of the LM, or just what the ngrams are? The description of these features in the readme sounds like we only care about the ngrams, not their counts. If that's so, should I just discard the count value when reading the LM?

**Comment by goodmami** [comment]
The interpretation of the path is unspecified, so you're free to implement it in the way you think best. My thought was that the Crubadan downloader and the language model reader would expect the same file/directory structure, so the parameter file would only require the single path. Because of issues like #14 you might want to create your own index file (e.g., at `{path}/index.json` or something), and that file would contain a mapping from lgcode-lgname pairs to a path pointing to its specific language model files.

As for the counts: the current definition of the Crubadan language model features care only about ngram presence, not count, so feel free to discard the counts when you read the models. But keep the counts stored on disk in case you want to change the features to utilize the counts.

**Comment by elirnm** [comment]
I'm getting memory errors when I try to read in the LM for all the (name, code) pairs at once, so I think I'm going to have to make `read_crubadan_language_model` return the LM just for one (name, code) pair.

**Comment by goodmami** [comment]
It looks like my (incomplete) version of the Crubadan data is ~1.5G on disk, so that's not surprising. Your proposed solution sounds reasonable.
