### ISSUE TITLE
Optionally output intermediate files

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#13]
The training and testing process produce some intermediate representations (e.g. feature vectors). An optional parameter that specifies an output path could allow us to inspect the processes for debugging.

**Comment by elirnm** [comment]
Do you have a preference for the parameter name?

**Comment by goodmami** [comment]
Something descriptive or intuitive I guess. Maybe `--temp-directory=DIR` where DIR is a directory where the results files will be stored.

**Comment by elirnm** [comment]
Closed with f88b4eb2c6cf9412f60fa43fc8b5770b930936b7
