### ISSUE TITLE
Crubadan data: languages with same ISO code won't download completely

### ISSUE THREAD

**Issue by elirnm** [xigt/lgid#14]
In the Crubadan data, different languages with the same ISO code can have different zip files, like [Ambulas (abt)](http://crubadan.org/languages/abt), [Ambulas Maprik (abt-x-maprik)](http://crubadan.org/languages/abt-x-maprik), and [Ambulas Wosera Kamu (abt-x-wosera)](http://crubadan.org/languages/abt-x-wosera) (all ISO `abt`).

Because the destination folder when downloading the data is formed from only the ISO code, and the `download_crubadan_data` function doesn't extract files when the directory already exists, the language files for `abt` will download, creating the `crubadan_lm/abt` folder, and the `abt-x-maprik` and `abt-x-wosera` files won't extract because the directory for their ISO code already exists.

Because these languages have the same ISO code they'd be treated the same by the lgid system, but skipping the downloads of the variants of `abt` reduces the amount of data we have for matching that language (especially because the basic `abt` Crubadan zip file is significantly smaller than the variant zip files). If the variants with the same ISO code could be combined it would give us a lot more data for the LMs.

**Comment by goodmami** [comment]
Hmm, that is a problem.

The straightforward solution is to detect these instances and provide unique directory names for the downloaded files (e.g., `abt-{langname}`, or even `abt-1`, `abt-2`, etc.).

However, there's a possibility that this would require some more significant changes to the architecture. E.g., you should ensure that the language mentions code doesn't index on solely on the language code, but always on the code-name pair.

**Comment by elirnm** [comment]
My planned solution is to name all the directories `<iso-code>_<crubadan-code>`, so Ambulas would be `abt_abt`, `abt_abt-x-maprik`, and `abt_abt-x-wosera`. I can do something else if you feel strongly about the undoubled languages having solely their ISO codes for directory names, but this seems like the simplest and most robust fix.

I'll make an index file for mapping (name, code) pairs to their directories.

**Comment by goodmami** [comment]
In that case, isn't the Crubadan code sufficient? It seems the iso-639 prefix is redundant, unless I'm missing something. The index would then map iso code + language name to Crubadan code (or paths, which is synonymous in this case).

And if you use Crubadan code or iso639+Crubadan, I'd vote for consistent over brevity and do it for all languages, not just the ambiguous ones.

But I guess I don't have strong feelings, if the solution is robust.

**Comment by elirnm** [comment]
Some languages in Crubadan have two entries - one in their native script (`<code>`) and one in Latin script (`<code>-Latn`). I think IGT is usually romanized, so should we use the Latin files?

And if there isn't an option for Latin script for a language, do we still want to include that LM or would that risk corrupting the model with 0% matches for all the LM features when the IGT entry has been romanized?

**Comment by elirnm** [comment]
Similarly, Ancient Hebrew has an entry with vowel diacritics and an entry with them stripped (both using Hebrew script).

**Comment by goodmami** [comment]
If it's no trouble, it makes sense to have the downloader fetch them all. And it seems appropriate to just use the Latin script variants unless you have some way of detecting native orthography in the IGTs.
