### ISSUE TITLE
build-odin-lm command

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#4]
Building the ODIN language model from training data should only be done once, rather than per run. This can be done by adding a `build-odin-lm` command and appropriate functions.

E.g., add to the docopt string the following:

```
Usage:
  [...]
  lgid [-v...] build-odin-lm CONFIG INFILE...
```

The output location of the language model is defined already in the config file:

```ini
[locations]
...
odin-language-model = %(lgid-dir)s/res/odin_lm
```

Use that location to create a directory or file. See the `download-crubadan-data` command for an example (although the process will be quite different since you're not downloading and extracting).

**Comment by goodmami** [comment]
Hey, that was pretty quick :)

However I really want to discourage having large data sources in the `res/` directory, especially when they are easily obtainable elsewhere, likely to change, and/or something we can generate from our scripts. It makes the commit diffs unwieldy and makes the repository explode (especially when the files change). Rather than including an entire copy of the current state of the ODIN data, it's better to point to the location of the ODIN data. Either list the ODIN data as a dependency (with instructions on how to get it), or include a script to download it (like with the Crubadan data). And then definitely don't check in the generated LM file; it should be generated by the script, not checked in.

If you must include large data files or collections, look into [Git LFS](https://git-lfs.github.com/), but the ODIN data and the generated LM data is not such a case.

**Comment by MackieBlackburn** [comment]
Ok thanks for the information. I will add a command to download the odin
data.

**Comment by goodmami** [comment]
Ok sounds good. You can either use the server at odin.xigt.org, or request from Patas (something like patas:/corpora/UWCL/odin/release/2.1/...). Let me know if you have questions about how to do either.

First thing to do is to remove the data from the repository, commit, then add the commands in a separate commit. This way the commit diff doesn't get swamped with all the removed files and hide the code additions.

Thanks!
