### ISSUE TITLE
L-LMw (ODIN word n-gram feature)

### ISSUE THREAD

**Issue by goodmami** [xigt/lgid#8]
Implement the word n-gram feature for ODIN data. Use the `word-n-gram-size` parameter in the config file and the word_ngrams() function in analyzers.py to compute the n-grams. Use the model stored at the `odin-language-model` path (defined in the config file).

**Comment by goodmami** [comment]
Is there a commit hash associated with the closure of this issue? If so, please link it here. You can also put "Resolves #..." in your commit message body, where ... is the issue number, and it will automatically close the issue when the commit is pushed to the primary branch.

**Comment by MackieBlackburn** [comment]
Here is a link to the commit:
https://github.com/xigt/lgid/commit/354a81fe642b9bf23d6443ac955b87bda60fe578

is that the best way to do that?

**Comment by goodmami** [comment]
> is that the best way to do that?

after the fact, yes. Otherwise it's a bit nicer to reference the issue in the commit message.

Thanks!
